### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by vanatteveldt** [vanatteveldt/nlpipe#10]
I do think we might need batch processing at some point, if you want to process 10k tweets you really don't want to keep track of 10k ids and do 10k HEAD requests to ask status. Maybe we can do something like:

```
POST api/modules/lemmatize/batch  < zipfile > ID
```

Server:
- creates ID from a unique hash (from individual file hashes?)
- creates a folder <repo>/lemmatize/batch/ID (if needed)
- unpacks the zipfile, queues all the files, and adds symlinks from the folder to the files
- returns the ID

```
HEAD api/modules/lemmatize/batch/ID
```

Response: status 200 (DONE if all done), 202 (PENDING if at least one pending), 404 (UNKNOWN) or 500 (ERROR if at least 1 error), with a status header indicating progress

```
GET api/modules/lemmatize/batch/ID -> zip file with all results
```

The workers don't need to change at all as everything goes through the normal queue system. 

@koheiw  Does this make sense?

**Comment by koheiw** [comment]
Too keep structure simple, it is better to put a lot of short texts in one document by the client side, and send get only one ID. For this, we can define two modes: single-line mode or multi-line mode. Short texts in Twitters are send in single line mode, where each line correspond to documents. Long articles like full-text news stories should be send in multi-line mode. Clients get results in a single XML files, but it will split tagged texts into documents when it is in single-line mode.

**Comment by koheiw** [comment]
Switching between these modes should be automatic. If \n is found within texts, ignoring end of the document, the client chose the multi-line mode.

**Comment by vanatteveldt** [comment]
I am hesitant to interpret the documents based on line feeds etc. I think that in principle the nlpipe should just pass documents to the preprocessing, and not touch input and output unless specifically asked.

What we could do is allow other input formats, e.g. csv or json, but then we need to have a clear definition of what we consider a "document" (e.g. unit of processing) and how to format output for multiple input texts in a single document?

**Comment by koheiw** [comment]
The procedure that I suggested does not modify input texts. Only out put from taggers are split when download. 

The problem with the zipping all files would be 1) instability in uploading via slow http connection, 2) inability to resume upload on connection failure, and 3) inceased complexity in file management. Packed does not allow taggers to start working until upload is completed.

**Comment by vanatteveldt** [comment]
I guess it doesn't really matter what format for batch files we accept as long as the users' choice of format is explicit, i.e. no "guessing". 

What I don't really understand is how a text-per-line overcomes the problems you mention, so I guess I don't quite understand what you propose. Can you sketch how you think the batch handling should go? I.e. is it a single document on the queue, or mutliple? Should the worker process it as a single text, or per line? And how does the output format look?

**Comment by koheiw** [comment]
I am suggesting this procedure to make the design more general while keeping the structure simple.

Single file upload disallow users to upload large files (sets of long documents), while allowing the client to resume upload from a file that failed to reach the server. As soon as files reaches the server, the system processes single-line and multi-line documents in the same way (the same was as the current process), and generate one XML file for each. These XML files are send back to client without tampering. The client splits the XML files based on tags that indicate end of lines (or paragraphs) for single-line documents, and keep those pieces of XML separately in somewhere.

**Comment by vanatteveldt** [comment]
Right, I am of course fine with clients doing whatever they want to do with the output :)

On HTTP, is there a standard mechanism to resume upload?
On direct FS access, wouldn't the system need a way to know upload is finished?

**Comment by koheiw** [comment]
Yes, for FS and FTP files need to be marked once upload is complete. Changes of file extension or relocations of files on upload completion should work, but users need to do this manually or let clients do this. I spoke for FTP, but I suggest you to leave it for a future function.

I will test how HTTP upload works in a way I proposed. If it works well with large number of documents, we do not really need FTP upload.

**Comment by vanatteveldt** [comment]
(implemented bulk api)
