### ISSUE TITLE
Output format / conversions

### ISSUE THREAD

**Issue by vanatteveldt** [vanatteveldt/nlpipe#11]
The corenlp worker currently returns corenlp's xml format. I think that it is probably best to keep input/output as close to the raw output of the tool we use as possible, and then offer some sort of standardized output for clients, especially a simple conll-style one-token-per-line csv output. Maybe make the client so you can ask

```
GET api/modules/corenlp_lemmatize/ID?format=csv
```

But then the server would somehow need to be able to convert the raw output into csv, which would create a dependency between the server and the workers (currently, you can setup the webserver on server X and only install e.g. corenlp on server Y that connects to X). I guess the server will just convert everything it knows about and disregard the rest. 

@koheiw what do you think?

**Comment by koheiw** [comment]
Raw XML is fine for me. The only problem would be the size of files, that contain information that users do not need. In this case, we can strip unnecessary fields from XML (convert them to CSV) when clients request downloaded.

**Comment by vanatteveldt** [comment]
Yes exactly, and presumably most users from e.g. R would only want the token information and convert it into a DFM asap anyway. With just corenlp XML that is fine, but if other tools offer different formats it would be nice to offer an optional conversion.

My current thinking is that all modules should have a convert_output(result, format) function that converts result to format (e.g. "csv", "json", "NAF", whatever) or errors if the format is not known.

We would then need to have a place where all workers need to be added (e.g. a variable in nlpipe.modules). The (FS and HTTP) client can then serve results in a format if he 'knows' the worker and the worker knows the format. This would also allow errors for unknown modules, currently a typo in the module name will simply hang. Agree?

**Comment by vanatteveldt** [comment]
I've created a base class for modules which has a `convert` function, see https://github.com/vanatteveldt/nlpipe/blob/master/nlpipe/module.py

TODO: add client options to fetch converted results

**Comment by vanatteveldt** [comment]
implemented format= options and csv format for corenlp/frog/alpino
